[ADD] snippet_google_map
Elico-Corp/odoo_community pull request #5
Opened 2016-09-07 02:55 UTC by noahzaozao

2016-09-13 01:51 UTC, seb-elico commented
@noahzaozao for the PRs to `odoo_community`, can you please specify in the PR the origin of the module? Also, would be great that in the same PR, you add a line in the root README to mention where this module comes from, the author and the license

2016-09-20 08:21 UTC, noahzaozao commented
@seb-elico  Done

2016-09-21 01:16 UTC, noahzaozao commented
@elicoidal @seb-elico @victormartinelicocorp Please review this README.md and we can merge the PR , thanks

2016-09-21 02:52 UTC, seb-elico commented
@elicoidal I think we should rename this module. e.g. `website_snippet_google_map` or `theme_snippet_google_map`. What do you think?

2016-09-21 03:22 UTC, elicoidal commented on README.md
no need to maintain this document

2016-09-21 03:22 UTC, elicoidal commented on snippet_google_map/LICENSE
> +Odoo Proprietary License v1.0
remove => repo level

2016-09-21 03:23 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +{
short headers

2016-09-21 03:23 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +    'version':'1.1',
version 8.0.1.0.0

2016-09-21 03:23 UTC, elicoidal commented on snippet_google_map/doc/index.rst
> +You need to install the *Less CSS* compiler to run this snippet
standart README header/footer

2016-09-21 03:24 UTC, elicoidal requested changes
Small details. LGTM
Change name as suggested

2016-09-21 11:21 UTC, noahzaozao commented
@seb-elico @elicoidal Please review this PR , thanks.

2016-09-21 11:31 UTC, seb-elico commented on README.md
@elicoidal what do you mean?

2016-09-21 11:32 UTC, seb-elico commented on snippet_google_map/__openerp__.py
> +    'version':'1.1',
@elicoidal well, this is an Odoo S.A. module. They don't even follow their own guidelines. Though, they're probably not part of OCA :stuck_out_tongue_closed_eyes:

2016-09-21 11:33 UTC, seb-elico approved these changes

2016-09-21 13:31 UTC, elicoidal commented on README.md
I think it is not needed to maintain the list of module in this file. Worst case there is a script in OCA to fill in the file

2016-09-21 13:31 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +    'version':'1.1',
I am confused: if this is Odoo module no need to modify anything

2016-09-21 13:33 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +    'version':'1.1',
I just dont remember

2016-09-22 01:34 UTC, noahzaozao commented
@seb-elico @elicoidal I've changed the version , please review this PR , thanks.

2016-09-22 01:54 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +# Copyright <YEAR(S)> <AUTHOR(S)>
Copyright 2010-today Odoo  SA

2016-09-22 01:55 UTC, elicoidal commented on snippet_google_map/__openerp__.py
> +# Copyright <YEAR(S)> <AUTHOR(S)>
Copyright 2015 Elico Corp

2016-09-22 06:14 UTC, seb-elico commented on README.md
@noahzaozao put back the description of the repo please

2016-09-22 06:16 UTC, seb-elico commented on snippet_google_map/__openerp__.py
> +# Copyright <YEAR(S)> <AUTHOR(S)>
Not Elico Corp, Odoo SA

2016-09-22 06:19 UTC, seb-elico commented on README.md
@elicoidal right now we don't have any standard/structured way to get the info about the modules. Since they are community modules, they don't necessarily follow the OCA guidelines such as the __openerp__.py entries. What is important for us is to make sure we know where the module comes from so that, in the future, we can, if necessary, update the modules in our repo based on the latest changes of the original module. And the best is that we import the module "as is" in our repo, do not touch anything inside (unless we find a bug for instance) and the only thing we have to do is fill the info in this `README.md` file!

2016-09-22 06:21 UTC, seb-elico commented on snippet_google_map/doc/index.rst
> +You need to install the *Less CSS* compiler to run this snippet
@elicoidal @noahzaozao I suggest we don't touch anything inside the modules since that was the original idea

2016-09-22 06:23 UTC, seb-elico commented
@elicoidal @noahzaozao Sorry for suggesting to change the name, I forgot we are on the odoo-community-addons repo (which is just a repo to backup some community modules, we are not supposed to change anything inside)

2016-09-22 06:24 UTC, seb-elico commented
@elicoidal @noahzaozao If we want to change the module, I suggest we move it to our [odoo-addons](https://github.com/Elico-Corp/odoo-addons) repo

2016-09-22 07:00 UTC, elicoidal commented
@seb-elico Agree.
Let's go fast here
cc @noahzaozao

2016-09-27 06:22 UTC, xie8899 commented
@elicoidal @seb-elico @noahzaozao Done

2016-09-27 10:11 UTC, seb-elico requested changes

2016-09-27 10:11 UTC, seb-elico commented on website_snippet_google_map/__openerp__.py
> +# @ 2016 Elico Corp, Odoo SA.
We are not the author. Only `Odoo S.A.` (not `Odoo SA.`)

2016-09-27 10:11 UTC, seb-elico commented on website_snippet_google_map/__openerp__.py
> +    'author': 'Elico Corp, Odoo S.A.',
We are not the author. Only `Odoo S.A.`

2016-09-27 10:15 UTC, xie8899 commented
@elicoidal @seb-elico @noahzaozao Done

2016-09-27 10:48 UTC, seb-elico approved these changes

2016-09-27 10:50 UTC, seb-elico commented
LGTM
@elicoidal @victormartinelicocorp @noahzaozao Can you please review this PR?

2016-09-27 16:54 UTC, elicoidal commented
LGTM

2016-09-27 16:54 UTC, merged